version: "3"
services:
  db:
    image: postgres:9.6.1-alpine
    ports:
      - "127.0.0.1:5432:5432"
  front-end:
    build: ./client
    volumes:
      - "./client/src:/app/src"
    ports:
      - "127.0.0.1:3000:3000"
  api:
    build: ./api
    volumes:
      - "./api/src:/app/src"
