version: "3"
services:
  postgres:
    image: postgres:9.6.1-alpine
  front-end:
    build: ./client
    volumes:
      - "./client/src:/app/src"
    ports:
      - "127.0.0.1:3000:3000"
  api:
    build: ./api
    volumes:
      - "./api/src:/app/src"
      - './api/public:/app/public'
    environment:
      PG_HOST: postgres
